const express = require("express");
const router = express.Router();
const Controller = require("../controller/Controller");
router.get("/users", Controller.getAll);
router.get("/users/:id", Controller.getById);
router.delete("/users/:id", Controller.deleteUser);
router.post("/users", Controller.postUser);
router.patch("/users/:id", Controller.patchUser);
router.put("/users/:id", Controller.putUser);
module.exports = router;
